frr version 9.1
frr defaults traditional
hostname pe1
log stdout
no ipv6 forwarding
service integrated-vtysh-config
!
! ---------- interfaces ----------
interface lo
 ip address 10.0.0.1/32
 ip ospf area 0
!
interface eth1
 description to-pe2 (core)
 ip address 10.1.12.1/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description to-ce1 (customer, primary)
 ip address 172.16.1.2/30
!
interface eth3
 description to-transit1 (upstream)
 ip address 203.0.113.1/30
!
! ---------- IGP ----------
router ospf
 ospf router-id 10.0.0.1
!
! ---------- BGP ----------
router bgp 65001
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.2 remote-as 65001
 neighbor 10.0.0.2 description iBGP-pe2
 neighbor 10.0.0.2 update-source lo
 !
 neighbor 172.16.1.1 remote-as 65100
 neighbor 172.16.1.1 description eBGP-ce1
 !
 neighbor 203.0.113.2 remote-as 65002
 neighbor 203.0.113.2 description eBGP-transit1
 !
 address-family ipv4 unicast
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.2 next-hop-self
  neighbor 172.16.1.1 activate
  neighbor 172.16.1.1 route-map CUSTOMER-IN in
  neighbor 203.0.113.2 activate
 exit-address-family
!
! Higher local-pref here makes pe1 the preferred exit for customer
! traffic across AS 65001. Change this to see the decision flip.
route-map CUSTOMER-IN permit 10
 set local-preference 200
!
line vty
!
