frr version 9.1
frr defaults traditional
hostname pe2
log stdout
no ipv6 forwarding
service integrated-vtysh-config
!
! ---------- interfaces ----------
interface lo
 ip address 10.0.0.2/32
 ip ospf area 0
!
interface eth1
 description to-pe1 (core)
 ip address 10.1.12.2/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description to-ce1 (customer, backup)
 ip address 172.16.2.2/30
!
interface eth3
 description to-transit1 (upstream)
 ip address 203.0.113.5/30
!
! ---------- IGP ----------
router ospf
 ospf router-id 10.0.0.2
!
! ---------- BGP ----------
router bgp 65001
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.1 remote-as 65001
 neighbor 10.0.0.1 description iBGP-pe1
 neighbor 10.0.0.1 update-source lo
 !
 neighbor 172.16.2.1 remote-as 65100
 neighbor 172.16.2.1 description eBGP-ce1
 !
 neighbor 203.0.113.6 remote-as 65002
 neighbor 203.0.113.6 description eBGP-transit1
 !
 address-family ipv4 unicast
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.1 next-hop-self
  neighbor 172.16.2.1 activate
  neighbor 172.16.2.1 route-map CUSTOMER-IN in
  neighbor 203.0.113.6 activate
 exit-address-family
!
! Default local-pref (100) — lower than pe1, so this path is backup.
route-map CUSTOMER-IN permit 10
 set local-preference 100
!
line vty
!
